[package]
name = "eve_merchant_bot"
version = "0.1.0"
authors = ["bopohob"]
edition = "2018"

[dependencies]
teloxide = { git = "https://github.com/BOPOHOB/teloxide" }
log = "0.4.8"
tokio = "0.2.11"
pretty_env_logger = "0.4.0"
json = "*"
