[package]
name = "eve_merchant_bot"
version = "0.1.0"
authors = ["bopohob"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
teloxide = "0.2.0"
log = "0.4.8"
tokio = "0.2.11"
pretty_env_logger = "0.4.0"
json = "*"
